# Generated by Django 4.2.4 on 2023-09-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='', upload_to='category_images/'),
        ),
    ]
