# Generated by Django 4.2.4 on 2023-09-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
